name: Build and Deploy Backend App

on:
  push:
    branches:
      - master
    paths:
      - 'src/backend/**'
      - '.github/workflows/backend.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src/backend'
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      
      - name: 'Upload Build Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

  deploy:
    runs-on: windows-latest
    needs: build
    environment: production
    
    steps:
      - name: 'Download Build Artifact'
        uses: actions/download-artifact@v4
        with:
          name: function-app
          path: ./output
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: 'fa-chessmate-swn-001'
          slot-name: 'Production'
          package: './output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EED845ACDDAF45E39EA29C508815709B }}

